spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://sprout-dev.cf42e2mq2dxs.ap-northeast-2.rds.amazonaws.com:3306/sprout-dev
    username: sprout
    password: Sprout123!!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 249724125506-bk9tr0ic63i0lud55abb498v5qo0lbv1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://dev-sprout-api-env.eba-v2trvj6g.ap-northeast-2.elasticbeanstalk.com/api/login/oauth2/code/google
            scope:
              - profile
              - email
              - openid

server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
    session:
      timeout: 1800
  port: 8080

cors:
  allowed-origins:
    - http://localhost:8080/api
    - http://localhost:3000/api
    - http://dev-sprout-api-env.eba-v2trvj6g.ap-northeast-2.elasticbeanstalk.com/api

url:
  redirect-url:  http://dev-sprout-api-env.eba-v2trvj6g.ap-northeast-2.elasticbeanstalk.com/api/login/success

jwt:
  access-token:
    secret: sproutAccesswhereUAccess-whereUAccesssproutURegister
    expiration: 3600
  refresh-token:
    secret: sproutRefreshwhereURefreshwhereURefresh-whereURegister
    expiration: 864000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**
